services:
  api:
    build: .
    ports:
      - 80:80
    environment:
      - DATABASE_HOST=db
      - POSTGRES_PASSWORD=ratestask
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - ./rates.sql:/docker-entrypoint-initdb.d/rates.sql
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=ratestask